import {Metadata} from "next"
import './globals.css'

export const metadata: Metadata = {
  title: {
    default: "Next.js Practice One",
    template: "%s | Next.js Practice One",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{padding: "1rem", backgroundColor: "lightblue"}}>
          <h2>Header</h2>
        </header>
        {children}
        <footer style={{padding: "1rem", backgroundColor: "lightblue"}}>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  )
}
